/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.stage.Stage;


public class App extends Application {
    private Stage stage;

    @Override
    public void start(Stage primaryStage) {
        this.stage = primaryStage;
        primaryStage.setTitle("Aplikasi JavaFX Saya");
        HomeScene();

    }
    //SCENE1 OPENING
    private void HomeScene() {

        Image logoImage = new Image("/pppp.jpg"); //foto
        ImageView imageView = new ImageView(logoImage);
        imageView.setFitWidth(360);
        imageView.setFitHeight(640);

        Pane root = new Pane();

        Button button1 = new Button("masuk");
        button1.setLayoutX(36);
        button1.setLayoutY(469);
        button1.setPrefHeight(55);
        button1.setPrefWidth(288);
        button1.setFont(Font.font("Inter", FontWeight.BOLD, 24));
        button1.setStyle(
                "-fx-background-color: transparent; -fx-border-color: #039BE5; -fx-border-width: 2px; -fx-text-fill: #039BE5; -fx-background-radius: 30; -fx-border-radius: 30;");
        button1.setOnAction(v -> ProfileScene());

        Text text1 = new Text("Hi, ");
        text1.setFont(Font.font("Inter", FontWeight.BOLD, 30));
        text1.setFill(Color.web("#EFF9FE"));
        text1.setLayoutX(30);
        text1.setLayoutY(90);

        Text text2 = new Text("Welcome TO");
        text2.setFont(Font.font("Inter", FontWeight.BOLD, 28));
        text2.setFill(Color.web("#EFF9FE"));
        text2.setLayoutX(30);
        text2.setLayoutY(129);

        Text text3 = new Text("My Application");
        text3.setFont(Font.font("Inter", FontWeight.BOLD, 24));
        text3.setFill(Color.web("#EFF9FE"));
        text3.setLayoutX(30);
        text3.setLayoutY(167);

        root.getChildren().addAll(imageView, button1, text1, text2, text3);

        Scene HomeScene = new Scene(root, 360, 640);
        stage.setScene(HomeScene);
        stage.show();
    }
    //SCENE2 
    private void ProfileScene() {

        Pane root = new Pane();

        Image logoImage = new Image("/pppp.jpg"); //foto
        ImageView imageView = new ImageView(logoImage);
        imageView.setFitWidth(360);
        imageView.setFitHeight(640);

        Image image1 = new Image(getClass().getResource("/pr.png").toExternalForm());

        ImageView imageView1 = new ImageView(image1);
        imageView1.setFitWidth(190);
        imageView1.setFitHeight(190);
        imageView1.setLayoutX(80);
        imageView1.setLayoutY(50);
        


        Text text4 = new Text("NAMA  : Muslih Khairu Alief Rahman ");
        text4.setFont(Font.font("Inter", FontWeight.BOLD, 16));
        text4.setFill(Color.web("#EFF9FE"));
        text4.setLayoutX(30);
        text4.setLayoutY(290);

        Text text5 = new Text("NIM      : H071231042");
        text5.setFont(Font.font("Inter", FontWeight.BOLD, 16));
        text5.setFill(Color.web("#EFF9FE"));
        text5.setLayoutX(30);
        text5.setLayoutY(318);

        // Membuat Scene 2
        root.getChildren().addAll(imageView, imageView1,text4,text5);
        Scene ProfileScene = new Scene(root, 360, 640);
        stage.setScene(ProfileScene);
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}